---
title: Tables
author: John Curtin
html-table-processing: none
---

Need to code out some examples of making tables using kableExtra and built in data.  Plan is to export these tables as images to allow there use regardless of the document format used to publish the manuscript.

```{r}
# set up environment
options(conflicts.policy = "depends.ok")
library(tidyverse)
library(kableExtra, exclude = "group_rows")
theme_set(theme_classic()) 

# Paths
# not needed for this demo but included as example for lab scripts
devtools::source_url("https://github.com/jjcurtin/lab_support/blob/main/format_path.R?raw=true")
path_models <- format_path("studydata/risk/models/ema")
path_data_shared <- format_path("studydata/risk/data_processed/shared")
path_data_ema <- format_path("studydata/risk/data_processed/ema")
```

```{r}
#| label: table-1
#| tbl-cap: Table 1. A table.

kbl(mtcars[1:10, 1:5]) |>
  kable_styling(bootstrap_options = "striped", full_width = F, position = "float_right") |>
  kable_styling(fixed_thead = T) |>
  add_header_above(c(" " = 1, "Group 1" = 2, "Group 2" = 2, "Group 3" = 1))

```

```{r}
#| label: table-2
#| tbl-cap: Table 2

knitr::kable(mtcars[1:2, 1:2], table.attr = "class=\"striped\"",
  format = "html")

```
